version: 2.1


variables:
  defaults: &defaults
    machine: # executor type
      image: ubuntu-2004:202104-01
    working_directory: ~/repo
    environment:
      GIT_LFS_SKIP_SMUDGE: "1"
  install_conda: &install_conda
    run:
      name: Install miniconda3
      command: |
        sudo apt-get update && sudo apt-get install -y build-essential libz-dev libcurl3-dev libarchive-dev gcc && \
        wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
        /usr/bin/bash ~/miniconda.sh -b && \
        rm ~/miniconda.sh && \
        ~/miniconda3/bin/conda clean -tipsy && \
        sudo ln -s ~/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
        echo ". ~/miniconda3/etc/profile.d/conda.sh" >> $BASH_ENV && \
        echo "conda activate base" >> $BASH_ENV
  install_sys_deps: &install_sys_deps
    run:
      name: install build-essential
      command: apt-get update --allow-releaseinfo-change && apt-get install -y build-essential libz-dev libcurl3-dev curl
  install_gitlfs: &install_gitlfs
    run:
      name: Install git-lfs
      command: conda install --yes -c conda-forge git-lfs && git lfs install
  install_additional_pkgs: &install_additional_pkgs
    run:
      name: Install hdf5 and pkgconfig
      command: conda install --yes -c conda-forge hdf5=1.10.6 pkgconfig
  restore_cache: &restore_cache
    restore_cache:
      keys:
        - source-v2-{{ .Branch }}-{{ .Revision }}
        - source-v2-{{ .Branch }}-
        - source-v2-master-
        - source-v2-
  setup: &setup
    run: 
      name: Setup Kipoi
      command: .circleci/setup.sh
  store_artifacts: &store_artifacts
    store_artifacts:
      path: test-reports
      destination: test-reports

jobs:

  # test only the newly added model
  test_new_models:
    <<: *defaults
    steps:
      - checkout
      - *install_conda   
      # - *install_sys_deps
      - *install_gitlfs
      - *install_additional_pkgs
      # - *restore_cache
      - *setup
      - run:
          name: run tests
          command: kipoi test-source kipoi --git-range master HEAD --verbose
      - run:
          name: run tests in common environmnets
          command: kipoi test-source kipoi --git-range master HEAD --common_env
          no_output_timeout: 60m
      - *store_artifacts
  
  # test all models in the repo
  test_all_models:
    parameters:
      num_of_shards: 
        type: integer
      shard_id:
        type: integer 
    <<: *defaults
    steps:
      - checkout
      - *install_conda   
      # - *install_sys_deps
      - *install_gitlfs
      - *install_additional_pkgs
      # - *restore_cache
      - *setup
      - run:
          name: run tests
          # Use  --clean_env to remove the environment of each model
          no_output_timeout: 60m
          command: kipoi test-source kipoi --all --num_of_shards << parameters.num_of_shards >> --shard_id << parameters.shard_id >>
      - *store_artifacts

  test_all_models_common_env:
    <<: *defaults
    steps:
      - checkout
      - *install_conda   
      # - *install_sys_deps
      - *install_gitlfs
      - *install_additional_pkgs
      # - *restore_cache
      - *setup
      - run:
          name: run tests in common environments
          no_output_timeout: 60m
          command: kipoi test-source kipoi --all --common_env
      - *store_artifacts

  date_release:
    <<: *defaults
    steps:
      - run:
          name: Tag and push
          command: |
            VERSION=$(date "+%Y-%m-%d")
            API_JSON=$(printf '{"tag_name": "v%s","target_commitish": "master","name": "v%s","body": "Release of version %s","draft": false,"prerelease": false}' $VERSION $VERSION $VERSION)
            curl --data "$API_JSON" https://api.github.com/repos/kipoi/models/releases?access_token=$GITHUB_TOKEN


workflows:
  version: 2.1

  # workflow for testing pushes and PRs
  test-models:
     jobs:
       - test_new_models:
           filters:
             branches:
               ignore:
                 - master
                 - test_all
  test-all-branch:
     jobs:
       - test_all_models:
           matrix:
             parameters:
               num_of_shards: [4]
               shard_id: [0, 1, 2, 3]
           filters:
             branches:
               only:
                 - master
                 - test_all
       - test_all_models_common_env:
           filters:
             branches:
               only:
                 - master
                 - test_all

  # workflow for testing all the models
  # on the master branch overnight
  kipoi-nightly-test:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - test_all_models:
          matrix:
            parameters:
              num_of_shards: [4]
              shard_id: [0, 1, 2, 3]
       - test_all_models_common_env


  weekly-tag:
     triggers:
       - schedule:
           cron: "0 0 * * 0"
           filters:
             branches:
               only:
                 - master
                 - fix-date-release
     jobs:
       - date_release
